apiVersion: v1
kind: Service
metadata:
  name: frontend-service 
spec:
  type: LoadBalancer  
  selector:
    app: frontend  # Select pods with the label "app: python-api"
  ports:
  - protocol: TCP
    port: 8501  # The port that the service exposes
    targetPort: 8501  # The port that the pods are listening on
