apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend  # Select pods with the label "app: redis"
  ports:
  - protocol: TCP
    port: 8000  # The port that the service exposes
    targetPort: 8000  # The port that the pods are listening on
